config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reminders
  root :to => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  validates_presence_of :title, :description, :remind_at
  belongs_to :user

  scope :reminding_today, -> { where(remind_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reminders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
    reminders_path
  end

  def after_sign_in_path_for(resource)
    reminders_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!

  def index
    @reminders = current_user.reminders.all
  end

  def new
    @reminder = current_user.reminders.new
  end

  def create
    @reminder = current_user.reminders.build(reminder_params)

    if @reminder.save
      redirect_to reminders_path, notice: 'Reminder created'
    else
      redirect_to reminders_path, notice: @reminder.errors.full_messages
    end
  end

  def edit
    @reminder = current_user.reminders.find(params[:id])
  end

  def update
    @reminder = current_user.reminders.find(params[:id])

    @reminder.assign_attributes(reminder_params)

    if @reminder.save
      redirect_to reminders_path, notice: 'Reminder updated'
    else
      redirect_to reminders_path, notice: @reminder.errors.full_messages
    end
  end

  def destroy
    @reminder = current_user.reminders.find(params[:id])

    if @reminder.destroy!
      redirect_to reminders_path, notice: 'Reminder deleted'
    else
      redirect_to reminders_path, notice: 'Error while deleting the reminder'
    end
  end

  private

  def reminder_params
    params.require(:reminder).permit(:title, :description, :remind_at, :recurrent)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminder_helper.rb
module ReminderHelper
  def flash_alerts_classes
    {notice: 'success', alert: 'warning', error: 'danger'}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminderApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'components/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reminders/_form.html.erb
<div class="row justify-content-center">
  <div class="col-6 mt-5">
    <div class="card">
      <div class="card-body">
        <%= simple_form_for @reminder do |f| %>
          <div class="form-group">
            <%= f.input :title, input_html: { class: 'form-control' } %>
          </div>

          <div class="form-group">
            <%= f.input :description, input_html: { class: 'form-control' }  %>
          </div>

          <div class="form-group">
            <label>
              <abbr title="required">*</abbr>
              Remind At
            </label>
            <%= f.input :remind_at, label: false %>
          </div>

          <div class="form-group form-check">
            <%= f.input :recurrent, label: 'Monthly Reminder?', input_html: { class: 'form-check-input' } %>
          </div>

          <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reminders/edit.html.erb
<%= render 'form' %>

app/views/reminders/index.html.erb
<% flash_alerts_classes.each do |key, klass| %>
  <% if flash[key].present? %>
    <div class="alert alert-<%= klass %> alert-dismissible mt-2">
      <div class="c-alert__text">
        <%= flash[key].html_safe %>
      </div>
    </div>
  <% end %>
<% end %>

<% if @reminders.present? %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Remind At</th>
      <th scope="col">Recurrent</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>

    <% @reminders.each do |reminder| %>
      <tr>
        <th scope="row"><%= reminder.title %></th>
        <td><%= truncate(reminder.description, :length => 80) %></td>
        <td><%= reminder.remind_at.strftime('%b %e, %Y') %></td>
        <td><%= reminder.recurrent %></td>
        <td>
          <%= link_to 'edit', edit_reminder_path(reminder) %> |
          <%= link_to 'delete', reminder_path(reminder), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>


<div class="">
  <%= link_to 'Create a new reminder', new_reminder_path, class: 'btn btn-primary' %>
</div>

app/views/reminders/new.html.erb
<%= render 'form' %>